name: Weiss Consulting
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4333
title: Weiss Consulting
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ecf4ff'
    - '#101203'
    - '#d89f82'
    - '#696282'
    - '#8e5031'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
