layout_spectrum: 0.09003857
typography_spectrum: 0.7477928
color:
  saturation: 0.231574
  lightness: 0.1550952
  brandStrength: 0.6245769
  rhythmicContrast: 0.4363445
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: Weiss Consulting
