name: Weiss Consulting
favicon: null
layout_spectrum: 0.24662
typography_spectrum: 0.7477928
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dfc1b1'
    - '#2b2b2b'
    - '#565656'
    - '#f1f1f3'
    - '#9d7f71'
  brandStrength: 0.625
  lightness: 0.1550952
  saturation: 0.231574
  rhythmicContrast: 0.4363445
purpose: []
