name: Weiss Consulting
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4333
title: Weiss Consulting
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#244282'
    - '#3f72b7'
    - '#fffffd'
    - '#16171b'
    - '#b3b9af'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
