name: Weiss Consulting
favicon: null
layout_spectrum: 0.09003857
typography_spectrum: 0.7477928
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.6245769
  lightness: 0.1550952
  saturation: 0.231574
  rhythmicContrast: 0.4363445
purpose: []
